# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://quickposes.app
title: Quick Poses for iPad
email: quickposes@fredericruaudel.fr
twitter: '@iGrumZ'
author: Frédéric Ruaudel
description: > # "Write an awesome description for your new site here. 
  An iOS app to help artists improve their drawing skills.
copyright: 'Copyright &copy; 2020 Frédéric Ruaudel. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/" target="_blank">Start Bootstrap</a>. Photos by bongkarn thanyakij from Pexels'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

appstore:
    title: Download QuickPoses for iOS on the App Store
    url: https://apps.apple.com/app/apple-store/id1510309896?pt=863578&ct=home&mt=8
